language: ruby
rvm:
  - 2.0.0
before_install:
  - wget http://sourceforge.net/projects/zaproxy/files/2.3.1/ZAP_2.3.1_Linux.tar.gz/download
  - tar -xvf download
  - git submodule update --init --recursive
before_script:
  - ls
  - cd vendor/railsgoat; ls
  - cd vendor/railsgoat; cat Gemfile
    # - cd vendor/railsgoat; bundle install
    # - cd vendor/railsgoat; bundle exec rake db:setup
    # - cd vendor/railsgoat; bundle exec rails server
script:
  - zapr --summary --debug --zap-path ./ZAP_2.3.1/zap.sh http://localhost:3000/
